### ISSUE TITLE
Build fails when using current main branch

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [EVerest/EVerest-archived#20]
**Describe the bug**
```
[ 51%] Generating ld-ev for module EnergyManager
Traceback (most recent call last):
  File "/home/thilo/.local/bin/ev-cli", line 5, in <module>
    from ev_cli.ev import main
  File "/home/thilo/.local/lib/python3.9/site-packages/ev_cli/ev.py", line 33, in <module>
    'interface_impl.cpp': env.get_template('interface-Impl.cpp.j2'),
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/thilo/.local/lib/python3.9/site-packages/ev_cli/templates/interface-Impl.cpp.j2", line 21, in template
    return {{ cmd.result.json_type|create_dummy_result }};
jinja2.exceptions.TemplateAssertionError: no filter named 'create_dummy_result'
make[2]: *** [modules/EnergyManager/CMakeFiles/ld-ev_EnergyManager.dir/build.make:80: generated/modules/EnergyManager/ld-ev.hpp] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:2750: modules/EnergyManager/CMakeFiles/ld-ev_EnergyManager.dir/all] Fehler 2
make: *** [Makefile:149: all] Fehler 2
```

**Comment by a-w50** [comment]
Hi Thilo,

did you installed the latest ev-cli tool?  What gives
`ev-cli --version`

**Comment by corneliusclaussen** [comment]
works in the latest main
