### ISSUE TITLE
Issue with successfully deploying EVerest

### ISSUE THREAD

**Issue by AndyChriss123** [EVerest/EVerest-archived#57]
After I tried to run this script:

`./run-scripts/run-sil.sh`

I have received this error:

```
2023-02-27 20:44:10.950807 [ERRO] iso15118_charge static void Log::error(const string&) :: ERROR - iso15118.shared.security (156): Can't find certfile or keyfile for SSL context
Traceback (most recent call last):
  File "/home/hlcc/checkout/everest-workspace/everest-core/build/dist/libexec/everest/modules/PyJosev/../../3rd_party/josev/iso15118/shared/security.py", line 145, in get_ssl_context
    password=load_priv_key_pass(KeyPasswordPath.SECC_LEAF_KEY_PASSWORD),
  File "/home/hlcc/checkout/everest-workspace/everest-core/build/dist/libexec/everest/modules/PyJosev/../../3rd_party/josev/iso15118/shared/security.py", line 263, in load_priv_key_pass
    raise exc
  File "/home/hlcc/checkout/everest-workspace/everest-core/build/dist/libexec/everest/modules/PyJosev/../../3rd_party/josev/iso15118/shared/security.py", line 251, in load_priv_key_pass
    with open(password_path, "r") as password_file:
FileNotFoundError: [Errno 2] No such file or directory: <KeyPasswordPath.SECC_LEAF_KEY_PASSWORD: '/home/hlcc/checkout/everest-workspace/everest-core/build/dist/libexec/everest/3rd_party/josev/iso15118/shared/pki/iso15118_2/private_keys/seccLeafPassword.txt'>
```

I have installed EVerest by following the quick guide as I did many times before but now I seem to fail at launching the simulator or running most scripts in /run-scripts directory. NodeRED is active on port 1880 with a blank initial setup.
If the solution to this problem seems like something rather obvious to you than I would be grateful if you could provide some help on this matter.
Thank you very much for your time and support.

```
System:
  Kernel: 5.15.80-rockchip64 aarch64 bits: 64 compiler: N/A
    Desktop: Xfce 4.16.0 Distro: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
Machine:
  Type: ARM System: OrangePi 4 LTS details: N/A serial: <filter>
CPU:
  Info: 2x 4-core model: N/A variant-1: cortex-a53 variant-2: cortex-a72
    bits: 64 type: MCP AMP arch: ARMv8 rev: 4
  Speed (MHz): avg: 1544 high: 1800 min/max: 408/1416:1800 cores: 1: 1416
    2: 1416 3: 1416 4: 1416 5: 1800 6: 1800 bogomips: N/A
  Features: Use -f option to see features
Graphics:
  Device-1: display-subsystem driver: rockchip_drm v: N/A bus-ID: N/A
  Device-2: rk3399-dw-hdmi driver: dwhdmi_rockchip v: N/A bus-ID: N/A
  Device-3: rk3399-mali driver: panfrost v: kernel bus-ID: N/A
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting
    unloaded: fbdev gpu: rockchip_drm,dwhdmi_rockchip,panfrost
    resolution: 1920x1080~60Hz
  OpenGL: renderer: Mali-T860 (Panfrost)
    v: 3.1 Mesa 23.1.0-devel (git-52f27cd 2023-02-27 jammy-oibaf-ppa)
    direct render: Yes
Audio:
  Device-1: simple-audio-card driver: asoc_simple_card bus-ID: N/A
  Device-2: rk3399-dw-hdmi driver: dwhdmi_rockchip bus-ID: N/A
  Device-3: simple-audio-card driver: asoc_simple_card bus-ID: N/A
  Sound Server-1: ALSA v: k5.15.80-rockchip64 running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: rk3399-gmac driver: rk_gmac_dwmac v: N/A port: N/A bus-ID: N/A
  IF: eth0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: uwe5622-wifi driver: N/A bus-ID: N/A
  IF-ID-1: wlan0 state: dormant mac: <filter>
Drives:
  Local Storage: total: 59.48 GiB used: 6.82 GiB (11.5%)
  ID-1: /dev/mmcblk2 model: SN64G size: 59.48 GiB
Partition:
  ID-1: / size: 57.87 GiB used: 6.82 GiB (11.8%) fs: ext4 dev: /dev/mmcblk2p1
  ID-2: /var/log size: 46.8 MiB used: 3.5 MiB (7.5%) fs: ext4
    dev: /dev/zram1
Swap:
  ID-1: swap-1 type: zram size: 1.89 GiB used: 0 KiB (0.0%) dev: /dev/zram0
Sensors:
  Missing: Required tool sensors not installed. Check --recommends
Info:
  Processes: 230 Uptime: 15m Memory: 3.77 GiB used: 1.29 GiB (34.1%)
  Init: systemd runlevel: 5 Compilers: gcc: 11.3.0 clang: 14.0.0-1ubuntu1
  Packages: 2020 Shell: Bash v: 5.1.16 inxi: 3.3.13
```

**Comment by AndyChriss123** [comment]
And running it with sudo outputs:

```
[sudo] password for hlcc: 
2023-02-27 23:21:33.380777 [INFO] manager          :: 8< 8< 8< ------------------------------------------------------------------------------ 8< 8< 8<
2023-02-27 23:21:33.381167 [INFO] manager          :: EVerest manager starting using /home/hlcc/checkout/everest-workspace/everest-core/config/config-sil.yaml
2023-02-27 23:21:33.381222 [INFO] manager          :: EVerest using MQTT broker localhost:1883
2023-02-27 23:21:33.381272 [INFO] manager          :: EVerest telemetry enabled
2023-02-27 23:21:34.666454 [INFO] everest_ctrl     :: everest controller process started ...
2023-02-27 23:21:34.683052 [INFO] everest_ctrl     :: Launching controller service on port 8849
Traceback (most recent call last):
  File "/home/hlcc/checkout/everest-workspace/everest-core/build/dist/lib/everest/everestpy/everest.py", line 17, in <module>
    module = importlib.import_module(f"{module_path.parent.name}.module")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/hlcc/checkout/everest-workspace/everest-core/build/dist/libexec/everest/modules/PyJosev/module.py", line 11, in <module>
    from iso15118.secc import SECCHandler
  File "/home/hlcc/checkout/everest-workspace/everest-core/build/dist/libexec/everest/modules/PyJosev/../../3rd_party/josev/iso15118/secc/__init__.py", line 5, in <module>
    from iso15118.secc.comm_session_handler import CommunicationSessionHandler
  File "/home/hlcc/checkout/everest-workspace/everest-core/build/dist/libexec/everest/modules/PyJosev/../../3rd_party/josev/iso15118/secc/comm_session_handler.py", line 19, in <module>
    from iso15118.secc.controller.interface import EVSEControllerInterface, ServiceStatus
  File "/home/hlcc/checkout/everest-workspace/everest-core/build/dist/libexec/everest/modules/PyJosev/../../3rd_party/josev/iso15118/secc/controller/interface.py", line 10, in <module>
    from iso15118.shared.messages.datatypes import (
  File "/home/hlcc/checkout/everest-workspace/everest-core/build/dist/libexec/everest/modules/PyJosev/../../3rd_party/josev/iso15118/shared/messages/__init__.py", line 1, in <module>
    from pydantic import BaseModel as PydanticBaseModel
ModuleNotFoundError: No module named 'pydantic'
2023-02-27 23:21:37.280191 [CRIT] manager         int boot(const boost::program_options::variables_map&) :: Module iso15118_charger (pid: 31363) exited with status: 256. Terminating all modules.
```

**Comment by SebaLukas** [comment]
You can ignore the above error message. The message is only relevant if you want to charge or test with Plug'n Charge. Then you need specific certificates.

I will change the error message into a warning in the next days. Then it will be clearer that the SIL runs without problems.

Thank you very much for your message.

PS: If you want to start the SIL via sudo, the Python modules should also be installed via sudo. Otherwise Python will not find the required modules.

**Comment by AndyChriss123** [comment]
Thank you for taking the time to help.
I will also do a fresh install as I did not create a virtual environment for the setup this time.
